language: android

android:
 components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools-24.3.3
    # - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

before_install: 
  # newest Android NDK
  - wget http://dl.google.com/android/ndk/android-ndk-r10e-linux-x86_64.bin
  - chmod a+x android-ndk-r10e-linux-x86_64.bin
  - ./android-ndk-r10e-linux-x86_64.bin -y | grep -v Extracting
  - export ANDROID_HOME=/usr/local/android-sdk
  - export ANDROID_NDK_HOME=`pwd`/android-ndk-r10e
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}
  - sudo apt-get -qq update
  - sudo apt-get -qq -y install yasm
  - sudo apt-get -qq -y install nasm
  - sudo apt-get -qq -y install curl
  - sudo apt-get -qq -y install ant
  - sudo apt-get -qq -y install rsync
  - sudo apt-get -qq -y install autoconf
  - sudo apt-get -qq -y install automake
  - sudo apt-get -qq -y install libtool
  - sudo apt-get -qq -y install pkgconf
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq -y install aptitude
  - sudo aptitude -qq -y update
  - sudo aptitude -qq -y install libstdc++6:i386 libgcc1:i386 zlib1g:i386 libncurses5:i386

script: make
